# This is a basic workflow to help you get started with Actions

name: PagingBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "feature/with-paging" branch
  push:
    branches: [ "feature/with-paging" ]
  pull_request:
    branches: [ "feature/with-paging" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: Pravin-Divraniya/Android-Compose-App
          path: origin
          token: ${{ github.token }}
          ref: feature/with-paging

      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      # Runs a single command using the runners shell
      - name: Grant execute permissions for gradlew //this step is only for macOS
        run: chmod +x https://github.com/Pravin-Divraniya/Android-Compose-App/blob/feature/with-paging/gradlew

      - name: Bundle 'release' with Gradle
        run: https://github.com/Pravin-Divraniya/Android-Compose-App/blob/feature/with-paging/gradlew bundleRelease
      
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}  
      - run: echo "Build status report=${{ job.status }}."
      # Runs a set of commands using the runners shell
      - name: Upload App Bundle
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}
      - name: Download AAB from build
        uses: actions/download-artifact@v1
        with:
           name: aab
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           tag_name: v1.0.0
           release_name: Paging release
      - name: Upload Release AAB
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: aab/app-release.aab
          asset_name: ${{ github.event.repository.name }}.aab
          asset_content_type: application/zip
      - run: echo "Upload returned with status=${{ job.status }}."
